config/routes.rb
Rails.application.routes.draw do
	root 'pages#welcome'
	get '/portfolio' => 'pages#portfolio'
	get '/about' => 'pages#about'
	get '/contact' => 'pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def welcome
	end
	
	def portfolio
	end
	
	def about
	end
	
	def contact
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto:500,100,300,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'unslider.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'portfolio' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="header">
	<div class="container">
		<div class="row">
			<div class="menu col-xs-8">
				<ul>
					<li><%= link_to "Welcome", root_path %></li>
					<li><%= link_to "Portfolio", portfolio_path %></li>
					<li><%= link_to "Blog", "https://medium.com" %></li>
					<li><%= link_to "About", about_path %></li>
					<li><%= link_to "Contact", contact_path %></li>
				</ul>
			</div>
			<div class="name col-xs-4">
				<h1>Ruby on Rails</h1>
			</div>
		</div>
	</div>
</div>

<%= yield %>

<div class="footer">
	<div class="container">
		<ul class="social_media">
			<li><%= link_to "Github", "https://github.com/razukc/portfolio", :class => "github" %></li>
			<li>LinkedIn</li>
			<li>Twitter</li>
		</ul>
		<p>&copy; 2015 Ruby on Rails</p>
	</div>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About me</h1>

app/views/pages/contact.html.erb
<h1>Contact me</h1>

app/views/pages/portfolio.html.erb
<div class="main portfolio">
	<div class="jumbotron slideshow"> 
		<div class="slideshow-container"> 
			<ul>
				<li class="slide"><img alt="Slide01" src="<%= image_path('slide01.jpg') %>"></li>
				<li class="slide"><img alt="Slide02" src="<%= image_path('slide02.jpg') %>"></li>
				<li class="slide"><img alt="Slide03" src="<%= image_path('slide03.jpg') %>"></li>
				<li class="slide"><img alt="Slide04" src="<%= image_path('slide04.jpg') %>"></li>
				<li class="slide"><img alt="Slide05" src="<%= image_path('slide05.jpg') %>"></li>
			</ul>
		</div> 
	</div>
		<div class="container">
			<div class="row"> 
				<a class="col-md-6 project" href="#"> 
					<div class="thumbnail-header"> 
						<div class="thumbnail-header-btn"></div> 
						<div class="thumbnail-header-btn"></div> 
						<div class="thumbnail-header-btn"></div> 
					</div> 
					<div class="thumbnail"> 
						<img alt="Project01" src="<%= image_path('project01.jpg') %>"> 
					</div> 
					<h3>TravelGo’s Booking App</h3> 
					<p>NGO liberal change-makers global time of extraordinary change, prevention climate change mobilize shift. Communities, social movement United Nations, Oxfam planned giving Global South humanitarian. Maximize.</p> 
				</a> 
				<a class="col-md-6 project" href="#"> 
					<div class="thumbnail-header"> 
						<div class="thumbnail-header-btn"></div> 
						<div class="thumbnail-header-btn"></div> 
						<div class="thumbnail-header-btn"></div> 
					</div> 
					<div class="thumbnail"> 
						<img alt="Project02" src="<%= image_path('project02.jpg') %>"> 
					</div> 
					<h3>Breather’s Reservation Site</h3> 
					<p>Pursue these aspirations free-speech healthcare sharing economy freedom. Beneficiaries gender rights raise awareness change movements provide. Eradicate, diversification inspire breakthroughs, incubation; solve Peace Corps. Innovate.</p> 
				</a> 
			</div>
			<div class="row"> <a class="col-md-6 project" href="#"> <div class="thumbnail-header"> <div class="thumbnail-header-btn"></div> <div class="thumbnail-header-btn"></div> <div class="thumbnail-header-btn"></div> </div> <div class="thumbnail"> <img alt="Project03" src="<%= image_path('project03.jpg') %>"> </div> <h3>EnVogue Events’ Portfolio</h3> <p>Informal economies; underprivileged, grantees transformative prosperity. Education best practices connect achieve plumpy'nut. Action Against Hunger; save the world, combat HIV/AIDS crowdsourcing eradicate inclusive facilitate collaborative.</p> </a> <a class="col-md-6 project" href="#"> <div class="thumbnail-header"> <div class="thumbnail-header-btn"></div> <div class="thumbnail-header-btn"></div> <div class="thumbnail-header-btn"></div> </div> <div class="thumbnail"> <img alt="Project04" src="<%= image_path('project04.jpg') %>"> </div> <h3>Gauntlet Gallery</h3> <p>Small-scale farmers; collaborative cities Bill and Melinda Gates best practices equity health theory of social change human experience. Tackle rural development relief worldwide respect, economic.</p> </a> </div>
			<div class="row"> 
				<a class="col-md-6 project" href="#"> <div class="thumbnail-header"> <div class="thumbnail-header-btn"></div> <div class="thumbnail-header-btn"></div> <div class="thumbnail-header-btn"></div> </div> <div class="thumbnail"> <img alt="Project05" src="<%= image_path('project05.jpg') %>"> </div> <h3>Koi Pond Online Visitors Guide</h3> <p>UNICEF, research Ford Foundation outcomes collaborative consumption turmoil change lives. Tackling, dignity, world problem solving small-scale farmers complexity rural. Emergent humanitarian, necessities effect, challenges of.</p> </a> <a class="col-md-6 project" href="#"> <div class="thumbnail-header"> <div class="thumbnail-header-btn"></div> <div class="thumbnail-header-btn"></div> <div class="thumbnail-header-btn"></div> </div> <div class="thumbnail"> <img alt="Project06" src="<%= image_path('project06.jpg') %>"> </div> <h3>Academy of Sciences  Newsletter</h3> <p>Aid collaborative global network overcome injustice honesty measures. Environmental, social impact carbon rights combat HIV/AIDS transform the world social innovation local effect. Free expression committed.</p> </a> </div>
		</div>
	</div>

app/views/pages/welcome.html.erb
<div class="main home">
	<div class="jumbotron">
		<div class="container">
			<h2>Hello. My name is <span class="highlight">Ruby on Rails</span> and I have creative ideas and build websites</h2>
			<%= link_to "View my work", portfolio_path, :class => "btn right" %>
		</div>
	</div>
</div>